### ISSUE TITLE
leader change not stable

### ISSUE THREAD

**Issue by pwzgorilla** [Dataman-Cloud/swan#237]
raft2017/01/05 11:47:45 INFO: 1 is starting a new election at term 728
raft2017/01/05 11:47:45 INFO: 1 became candidate at term 729
raft2017/01/05 11:47:45 INFO: 1 received MsgVoteResp from 1 at term 729
raft2017/01/05 11:47:45 INFO: 1 became leader at term 729
raft2017/01/05 11:47:45 INFO: raft.node: 1 elected leader 1 at term 729
INFO[2017-01-05 11:47:45] Now leader is change to 127.0.0.1:9999       
raft2017/01/05 11:47:47 INFO: 1 [logterm: 729, index: 1129, vote: 1] rejected MsgVote from 3 [logterm: 671, index: 20] at term 729
raft2017/01/05 11:47:50 INFO: 1 [term: 729] received a MsgVote message with higher term from 3 [term: 730]
raft2017/01/05 11:47:50 INFO: 1 became follower at term 730
raft2017/01/05 11:47:50 INFO: 1 [logterm: 729, index: 1129, vote: 0] rejected MsgVote from 3 [logterm: 671, index: 20] at term 730
raft2017/01/05 11:47:50 INFO: raft.node: 1 lost leader 1 at term 730

**Comment by xiaods** [comment]
should be add testing code to cover the case.
