### ISSUE TITLE
[Call for Discussion] Decouple interface `store` into small,  separated interfaces base on usage/features

### ISSUE THREAD

**Issue by cmingxu** [Dataman-Cloud/swan#26]
For now we have all data access layer into single one `store` interface,  my concern is that it is  going to be got explode when  too many feature added in.

What I suggest is we are going to separated into small chunk of interfaces like `AppStore`, `TaskStore`, `IPAMStore`, etc.

Any suggestion?

**Comment by pwzgorilla** [comment]
+1 
seems like a good idea
