### ISSUE TITLE
use macvlan on docker-machine/virtual box

### ISSUE THREAD

**Issue by wuti1609** [Dataman-Cloud/swan#296]
创建 vm 时，需要加入以下参数：
--virtualbox-hostonly-nicpromisc allow-all
该参数取值默认是 deny，会导致 vm 网卡无法开启混淆模式。
https://docs.docker.com/machine/drivers/virtualbox/

**Comment by xiaods** [comment]
对于网络，应该全面采用CNI的网络方案。Mesos，K8S都是采用CNI来对网络层进行抽象。请关注
