### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by cookieY** [Dataman-Cloud/swan#356]
22:03:45 swan | 2017-02-15 22:03:45.229343 C | rafthttp: newURLs [0.0.0.0:2111] should never fail: URL scheme must be http, https, unix, or unixs: 0.0.0.0:2111
22:03:50 swan | time="2017-02-15 22:03:50" level=error msg="Add node failed, Error: raft: failed to process the request: node losts leader status" 
22:03:50 swan | time="2017-02-15 22:03:50" level=info msg="192.168.212.3 - - [15/Feb/2017:22:03:50 +0800] \"POST /v_beta/nodes HTTP/1.1\" 500 61" 
22:03:50 swan | time="2017-02-15 22:03:50" level=error msg="register to http://192.168.212.3:9999/v_beta/nodes got error: raft: failed to process the request: node losts leader status" 
22:03:55 swan | time="2017-02-15 22:03:55" level=error msg="Add node failed, Error: raft: failed to process the request: node losts leader status" 
22:03:55 swan | time="2017-02-15 22:03:55" level=info msg="192.168.212.3 - - [15/Feb/2017:22:03:55 +0800] \"POST /v_beta/nodes HTTP/1.1\" 500 61" 
22:03:55 swan | time="2017-02-15 22:03:55" level=error msg="register to http://192.168.212.3:9999/v_beta/nodes got error: raft: failed to process the request: node losts leader status"

**Comment by cmingxu** [comment]
ping @upccup

**Comment by upccup** [comment]
@cookieY thanks for your feedback.   I was try to reslove this in https://github.com/Dataman-Cloud/swan/pull/354/files, please tty again.

**Comment by cookieY** [comment]
thanks， I changed the code based on the information you provided, but when i started it , one error has been found 
"
ERRO[2017-02-16 18:00:26] register to http://0.0.0.0:9999/v_beta/nodes got error: leader state has been losted
"
and I can't access the 80 port through the browser 

my go-version is 1.7

**Comment by cmingxu** [comment]
@cookieY could you try curl 80 port, if response status is 502, that should be expected.  
BTW, please add my wechat  xcm002 we would like to help you about this.

**Comment by xiaods** [comment]
@cookieY any update?

**Comment by xiaods** [comment]
@cookieY close this issue, if you have any question, please submit new issue. thanks a lot.
