### ISSUE TITLE
增加应用发布过程中的报错信息

### ISSUE THREAD

**Issue by wuti1609** [Dataman-Cloud/swan#374]
1、发布应用时资源不足，直接在实例状态上提示用户资源不足；
2、镜像下载失败，在实例状态上显示实例无法启动，在该实例的日志里展示下载镜像失败，这应该是executor产生的log；
3、镜像文件损坏，在实例状态上显示实例无法启动，在该实例的日志里展示镜像文件损坏，这应该是executor产生的log；
4、容器启动失败，在实例状态上显示实例无法启动，在该实例的日志里展示容器启动失败的具体原因，这应该是STDOUT或STDERR的内容。

其他应用运行时由于各种故障（外部硬件故障或软件自身故障）被重启迁移的信息也应该在实例详情里展示。

**Comment by cmingxu** [comment]
**  Any task unable to got any offer will be marked as slot_pending_offer state, which indicates resources unavailable.

**  swan was able to retrieve any message that `Mesos` report to `Swan` after any task_failed, so any `image not found` or `incorrect image` could be spot by `Swan` user easily.

** we not intend to fetch any stdout or stderr as these files in standbox directory might be extremely large data file, plus `Swan` is not intend to access any file which locate on `Mesos` agent, as any operations on agent might through master.
