### ISSUE TITLE
app 和 slot 的 dns 地址，去掉 gateway

### ISSUE THREAD

**Issue by wuti1609** [Dataman-Cloud/swan#387]

**Comment by cmingxu** [comment]
@wuti1609 for the time present, we support DNS to access slot with the following rules:

for replicates apps we we DNS records 0.nginx.xcm.cluster.swan.com(SRV),  0.nginx.xcm.cluster.swan.com(A ip address running the task),  nginx.xcm.cluster.swan.com(A ip list for running the app); for fixed apps we have DNS  0.mysql.xcm.cluster.swan.com(A),mysql.xcm.cluster.swan.com(A which means task ips assigned by user).


for DNS record with "gateway" will return gateway ip address.

**Comment by xiaods** [comment]
it seems presents two use case for dns record, the internal record and ingress record. in swarm era, the internal record is service name, such *nginx*, don't have domain record, and for ingress record, it design to readiness url. i think we need proposal a detail rule for this use case.

**Comment by xiaods** [comment]
fixed by split proxy concept and dns concepts.
