### ISSUE TITLE
Any plan of supporting configurable `MaxLength` for `utils/selection`?

### ISSUE THREAD

**Issue by xychu** [Dataman-Cloud/swan#392]
Now they are just constant definitions like
`const qualifiedNameMaxLength int = 63` and `const LabelValueMaxLength int = 63`.

When use `swan` as an upstream project, we'd like to use some of our own defined fields or labels with different length limits, so it would be nice for us that swan could make it configurable.

**Comment by upccup** [comment]
@xychu we want swan config is the less the better, how about add the constant value.
