### ISSUE TITLE
Does swan support passing registry auth info?

### ISSUE THREAD

**Issue by xychu** [Dataman-Cloud/swan#401]
We need to support third-party registry, any way to pass the auth info using swan?

**Comment by cmingxu** [comment]
short answer is NO, but we can achieve this by adding extra config to mesos agent when start any slave.

**Comment by cmingxu** [comment]
https://github.com/apache/mesos/blob/master/src/docker/docker.cpp#L1504

**Comment by xychu** [comment]
If we add the docker registry auth info on slave level, then maybe we lose the ability to control perms of docker pull, because other's auth info will be in that file too.

**Comment by cmingxu** [comment]
swan support URI fetch before launching any task, so fetch auth info into sandbox directory would be better.

**Comment by xychu** [comment]
Then everything is fine :-)
