### ISSUE TITLE
是否会支持 host 模式

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#405]

**Comment by xiaods** [comment]
我理解是让Docker来管理网络。不要屏蔽Host模式。

**Comment by cmingxu** [comment]
Swan will not support host mode directly as host mode would made application management complex and we still didn't think out better idea to do this.

But we can achieve this by assign fixed IP to any task which have such need.

**Comment by xiaods** [comment]
it's depends. we want to support flexible network environment to try the use case. because swan don't care the network implements, so why ignore native docker network feature?

**Comment by xiaods** [comment]
Swarm也遇到这样的问题：
https://github.com/docker/docker/issues/25873#issuecomment-283874532

+1 for the need of host mode. The overlay network of swarm mode has performance penalty
