### ISSUE TITLE
容器网络如何选型

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#406]

**Comment by xiaods** [comment]
Mesos支持CNI，当前Swan是直接调用Docker，Docker是支持CNM。

**Comment by cmingxu** [comment]
Mesos have four ways to assign network to any docker executor, they are HOST, BRIDGE， NONE and USER, what we did is that use __BRIDGE__ for replicates apps and __USER__ for fixed apps. 

for more info please check [this](https://github.com/apache/mesos/blob/master/src/docker/docker.cpp#L645) out.

**Comment by xiaods** [comment]
mesos have a general interface to handle docker, but currently we focus on docker network solution, so we need give a workable solution on it. swan need more use case to handle.
