### ISSUE TITLE
swan 可以向容器内部内置需要的环境变量

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#421]
比如网络方面注入索引端口对应的端口port，包括host模式

**Comment by pwzgorilla** [comment]
@pangzheng 能列举几个需要加的吗？

**Comment by pwang7** [comment]
Swan给容器动态分配端口，这个功能很实用。
进一步，将来做编排的时候，编排文件里会要用端口名称作为变量来引用随机分配的端口。

**Comment by cmingxu** [comment]
SWAN_CONTAINER_PORT_WEB=80
SWAN_HOST_PORT_WEB=31000
SWAN_IP=192.168.1.213 \# both fixed & replicates
