### ISSUE TITLE
panic: cannot use none as id

### ISSUE THREAD

**Issue by pwzgorilla** [Dataman-Cloud/swan#426]
tiseAddr: Status: Labels:map[] Role:agent RaftID:0} 
 
panic: cannot use none as id

goroutine 1 [running]:
github.com/Dataman-Cloud/swan/vendor/github.com/coreos/etcd/raft.newRaft(0xc420176200, 0xe1)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/coreos/etcd/raft/raft.go:268 +0xda4
github.com/Dataman-Cloud/swan/vendor/github.com/coreos/etcd/raft.RestartNode(0xc420176200, 0x0, 0x0)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/coreos/etcd/raft/node.go:215 +0x43
github.com/Dataman-Cloud/swan/src/manager/raft.(*Node).StartRaft(0xc420192000, 0x2b600f8, 0xc420122ec0, 0xc420176580, 0x1, 0x1, 0x1, 0x1b0b520, 0x1cb84b0)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/src/manager/raft/raft.go:196 +0xd13
github.com/Dataman-Cloud/swan/src/manager.(*Manager).start(0xc42010aea0, 0x2b600b8, 0xc420018250, 0xc420176580, 0x1, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/src/manager/manager.go:201 +0x21e
github.com/Dataman-Cloud/swan/src/manager.(*Manager).InitAndStart(0xc42010aea0, 0x2b600b8, 0xc420018250, 0x2b600b8, 0xc420018250)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/src/manager/manager.go:178 +0x100
main.StartManager(0xc420106500, 0x100, 0xc420106500)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/main.go:313 +0x214
github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli.HandleAction(0x16840a0, 0x179f130, 0xc420106500, 0xc420124200, 0x0)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli.Command.Run(0x1776c0d, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x177b94d, 0xd, 0x0, ...)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc42005eb60, 0xc420106280, 0x0, 0x0)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli.Command.startApp(0x177838b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x177eaab, 0x12, 0x0, ...)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli/command.go:280 +0x824
github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli.Command.Run(0x177838b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x177eaab, 0x12, 0x0, ...)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli/command.go:79 +0x14c7
github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli.(*App).Run(0xc42005e9c0, 0xc420010120, 0x6, 0x6, 0x0, 0x0)
	/usr/local/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()

**Comment by xiaods** [comment]
instead of zk, so this is outdate bug.
