### ISSUE TITLE
`taskPortMappings` is null 

### ISSUE THREAD

**Issue by cmingxu** [Dataman-Cloud/swan#431]
[
    {
        "appID": "nginx-xcm-datamanmesos",
        "appMode": "replicates",
        "ip": "192.168.1.175",
        "taskID": "0-nginx-xcm-datamanmesos",
        "taskPortMappings": null,
        "url": "0.nginx.xcm.datamanmesos"
    }
]

**Comment by xiaods** [comment]
有问题？
