### ISSUE TITLE
Show slotID in task info.

### ISSUE THREAD

**Issue by liuzhengbaihe** [Dataman-Cloud/swan#442]
I want to get slotID when get task info. Currently, the returned value is like this:
"tasks": [
        {
            "agentHostname": "192.168.1.162",
            "agentID": "7eb8072d-25f4-463b-a743-84767f5fd512-S15",
            "appId": "nginx-yaoyun-datamanmesos",
            "cpu": 0.01,
            "created": "2017-03-13T07:55:21.055349122Z",
            "healthy": true,
            "id": "0-nginx-yaoyun-datamanmesos-edd6bede0fb8428ab05efd89f5c6d6b9",
            "image": "nginx:1.10",
            "mem": 16,
            "offerID": "7eb8072d-25f4-463b-a743-84767f5fd512-O2286442",
            "status": "slot_task_running",
            "versionId": "1489391720"
        }

reflected apis:
http:swan_url:port/v_beta/apps/xxxx
http:swan_url:port/v_beta/apps/xxxx/tasks/x

**Comment by cmingxu** [comment]
see https://github.com/Dataman-Cloud/swan/pull/441

**Comment by liuzhengbaihe** [comment]
cool

**Comment by cmingxu** [comment]
Done
