### ISSUE TITLE
No healthCheck field when get app info

### ISSUE THREAD

**Issue by liuzhengbaihe** [Dataman-Cloud/swan#444]

**Comment by liuzhengbaihe** [comment]
@cmingxu

**Comment by cmingxu** [comment]
Thanks for the feedback, will look into it ASAP.

**Comment by cmingxu** [comment]
@liuzhengbaihe 

{
  "id": "nginx-xcm-cluster",
  "name": "nginx",
  "instances": 3,
  "runningInstances": 3,
  "runAs": "xcm",
  "priority": 100,
  "created": "2017-03-16T21:59:17.747652336+08:00",
  "updated": "2017-03-16T21:59:17.747652403+08:00",
  "mode": "replicates",
  "state": "normal",
  "tasks": [
   {
    "id": "0-nginx-xcm-cluster-21cd084df5fa4390b1f18769c3be8ada",
    "appID": "nginx-xcm-cluster",
    "slotID": "0-nginx-xcm-cluster",
    "versionID": "1489672757",
    "status": "slot_task_running",
    "offerID": "012a2a3c-c9c4-48db-ab19-c7eb3dda8ef0-O45287",
    "agentID": "012a2a3c-c9c4-48db-ab19-c7eb3dda8ef0-S0",
    "agentHostname": "114.55.130.152",
    "cpu": 0.01,
    "mem": 5,
    "ports": [
     31000
    ],
    "created": "2017-03-16T21:59:17.760280166+08:00",
    "image": "nginx:1.10",
    "healthy": true
   },
   {
    "id": "1-nginx-xcm-cluster-f68b2d4ad0e2444f9723ae4dd575594f",
    "appID": "nginx-xcm-cluster",
    "slotID": "1-nginx-xcm-cluster",
    "versionID": "1489672757",
    "status": "slot_task_running",
    "offerID": "012a2a3c-c9c4-48db-ab19-c7eb3dda8ef0-O45289",
    "agentID": "012a2a3c-c9c4-48db-ab19-c7eb3dda8ef0-S0",
    "agentHostname": "114.55.130.152",
    "cpu": 0.01,
    "mem": 5,
    "ports": [
     31001
    ],
    "created": "2017-03-16T21:59:21.003709458+08:00",
    "image": "nginx:1.10",
    "healthy": true
   },
   {
    "id": "2-nginx-xcm-cluster-95fbb78882f64ebea07997ae3f3c9616",
    "appID": "nginx-xcm-cluster",
    "slotID": "2-nginx-xcm-cluster",
    "versionID": "1489672757",
    "status": "slot_task_running",
    "offerID": "012a2a3c-c9c4-48db-ab19-c7eb3dda8ef0-O45291",
    "agentID": "012a2a3c-c9c4-48db-ab19-c7eb3dda8ef0-S0",
    "agentHostname": "114.55.130.152",
    "cpu": 0.01,
    "mem": 5,
    "ports": [
     31002
    ],
    "created": "2017-03-16T21:59:25.013301587+08:00",
    "image": "nginx:1.10",
    "healthy": true
   }
  ],
  "currentVersion": {
   "id": "1489672757",
   "appName": "nginx",
   "cpus": 0.01,
   "mem": 5,
   "instances": 3,
   "runAs": "xcm",
   "priority": 100,
   "container": {
    "type": "DOCKER",
    "docker": {
     "image": "nginx:1.10",
     "network": "bridge",
     "parameters": [
      {
       "key": "label",
       "value": "APP_ID=nginx"
      }
     ],
     "portMappings": [
      {
       "containerPort": 80,
       "name": "web",
       "protocol": "tcp"
      }
     ],
     "privileged": true
    },
    "volumes": [
     {
      "containerPath": "/data",
      "hostPath": "/home",
      "mode": "RW"
     }
    ]
   },
   "healthCheck": {
    "protocol": "http",
    "portName": "web",
    "path": "/",
    "consecutiveFailures": 500,
    "gracePeriodSeconds": 5,
    "intervalSeconds": 1,
    "timeoutSeconds": 4,
    "delaySeconds": 2
   },
   "killPolicy": {
    "duration": 5
   },
   "mode": "replicates"
  }
 }

**Comment by liuzhengbaihe** [comment]
@cmingxu , thanks.
