### ISSUE TITLE
error msg is not correct if healthCheck field contains nothing when deploy app

### ISSUE THREAD

**Issue by liuzhengbaihe** [Dataman-Cloud/swan#450]
run command:
 http post 172.28.128.3:9999/v_beta/apps @example/template-replicates-nginx.json

in template-replicates-nginx.json:
healthCheck is set like below:
"healthCheck": {}

error msg is like: "no port name  found in docker's PortMappings"
actually port name has been set in PortMappings.

**Comment by liuzhengbaihe** [comment]
@cmingxu

**Comment by cmingxu** [comment]
portname in health check section should match that defined in portmappings

**Comment by liuzhengbaihe** [comment]
So the msg should change in swan code.

**Comment by liuzhengbaihe** [comment]
https://github.com/Dataman-Cloud/swan/pull/451
