### ISSUE TITLE
当应用状态为creating时删除该应用失败。

### ISSUE THREAD

**Issue by liuzhengbaihe** [Dataman-Cloud/swan#457]
当应用状态为creating, instance状态为slot_task_pending_offer时，删除该应用，应用状态将变为并保持deleting状态。

**Comment by liuzhengbaihe** [comment]
@cmingxu , @pwzgorilla

**Comment by pwzgorilla** [comment]
@liuzhengbaihe  测试了可以删掉 我继续重现！
