### ISSUE TITLE
"make docker-build"  is very slow, always hang on the process of downloading packages.

### ISSUE THREAD

**Issue by liuzhengbaihe** [Dataman-Cloud/swan#471]
Suggest put "sh -c "apk update && apk add make && apk add git && make"" into base image or change other build way. Seems waste time  running update and add package  when run docker-build every time.

@cmingxu , @pwzgorilla

**Comment by pwzgorilla** [comment]
@liuzhengbaihe 解决了 你可以试试 飞一般的感觉

**Comment by xiaods** [comment]
closed by above comments.
