### ISSUE TITLE
delete app swan crash

### ISSUE THREAD

**Issue by pwzgorilla** [Dataman-Cloud/swan#490]
time="2017-03-31 11:20:39" level=info msg="192.168.1.73 - - [31/Mar/2017:11:20:39 +0000] \"DELETE /v_beta/apps/0002.nmg.nmgtest HTTP/1.1\" 204 0" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa9 pc=0xa7f373]

goroutine 493159 [running]:
panic(0xcbb380, 0xc820012060)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/Dataman-Cloud/swan/src/manager/framework/state.(*Slot).KillTask(0x0)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/state/slot.go:130 +0x23
github.com/Dataman-Cloud/swan/src/manager/framework/state.(*StateDeleting).Step(0xc82070b100)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/state/state_deleting.go:71 +0x33d
github.com/Dataman-Cloud/swan/src/manager/framework/state.(*StateMachine).Step(0xc820263740)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/state/app_state_machine.go:75 +0x39
github.com/Dataman-Cloud/swan/src/manager/framework/state.(*App).Step(0xc82054b740)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/state/app.go:373 +0x28
github.com/Dataman-Cloud/swan/src/manager/framework/state.(*Slot).SetHealthy(0xc82068c210, 0x0)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/state/slot.go:406 +0x5c
github.com/Dataman-Cloud/swan/src/manager/framework/scheduler.UpdateHandler(0xc82075c510, 0xc82075c510, 0x0, 0x0)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/scheduler/hdl_update.go:59 +0x1631
github.com/Dataman-Cloud/swan/src/manager/framework/scheduler.(*Handler).Process(0xc82075c510, 0x7fcc95e771d0, 0xc82075c540)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/scheduler/handler.go:43 +0x301
created by github.com/Dataman-Cloud/swan/src/manager/framework/scheduler.(*HandlerManager).Handle
	/go/src/github.com/Dataman-Cloud/swan/src/manager/framework/scheduler/handler_manager.go:58 +0x36e
[root@srymaster2 ~]#

**Comment by xiaods** [comment]
这个bug还有吗？

**Comment by pwzgorilla** [comment]
没了
