### ISSUE TITLE
could swan to be compatible with the marathon's docker label

### ISSUE THREAD

**Issue by douzl** [Dataman-Cloud/swan#493]
We use the docker labels to mark the information of the container created by Swan or Marathon, include cluster, user, app, task. But they use the different label key, that increase the difficulty when we handle the data from the containers. Following are the list of the different label's name, please think about how to fix.

Marathon:
  cluster LABEL: "VCLUSTER"
  app LABEL: "APP_ID"
  task ENV: "MESOS_TASK_ID"
  
Swan:
   cluster LABEL: "DM_CLUSTER, VCLUSTER"
  app LABEL: "APP_ID, DM_APP"
  user LABEL: "DM_USER, USER_NAME"
  group LABEL: "GROUP_NAME"
  task ENV: "MESOS_CONTAINER_NAME"

@cmingxu @xychu @upccup , we need make sure the name of label and ENV  for the monitor tools.

**Comment by xychu** [comment]
@douzl  As discussed, we(borg + swan) will use DM_ as prefix for all the label name.
Borg has one in-progress issue.
So after that task finished, the labels will be:
cluster LABEL: "DM_CLUSTER, DM_VCLUSTER"
app LABEL: "DM_APP", (no more "APP_ID")
user LABEL: "DM_USER(swan added, equal to runAs), DM_USER_NAME(borg added, equal to the creator user name)"
group LABEL: "DM_GROUP_NAME"(borg added, equal to the creator's current group name)

**Comment by upccup** [comment]
@xychu 👍   use app and cluster replace app_id and cluster_id can simplify work.

**Comment by xychu** [comment]
UPDATE:  add DM_APP_ID back.
So  app LABELs will be: 
"DM_APP": App Name,
"DM_APP_ID": App ID

**Comment by pwzgorilla** [comment]
done
