### ISSUE TITLE
design discuss

### ISSUE THREAD

**Issue by pwzgorilla** [Dataman-Cloud/swan#514]
swan 在功能上能不能拆成独立的二进制包呢，swan-master swan-agent swan-proxy swan-dns。 二进制独立，源码放到一个repo里。

**Comment by xiaods** [comment]
合理。就这么搞。

**Comment by xiaods** [comment]
后面设计应该在docs里面建立一个文档留下设计思路，帮助开发者了解和熟悉当前的方向。

**Comment by xiaods** [comment]
最少现在比较清晰的设计是：
swan manager
swan proxy
swan dns

**Comment by xiaods** [comment]
http://confluence.dataman-inc.com/pages/viewpage.action?pageId=4457045
