### ISSUE TITLE
高可用测试swan后，swan服务不可用

### ISSUE THREAD

**Issue by ss75710541** [Dataman-Cloud/swan#521]
![image](https://cloud.githubusercontent.com/assets/5858487/25034458/4513dde2-2119-11e7-99a3-8281f1986938.png)

**Comment by ss75710541** [comment]
上面是某一个swan 报的异常

**Comment by pwzgorilla** [comment]
新版本已经解决了该问题

**Comment by cmingxu** [comment]
这是数据恢复的问题， 和leader election没关系

**Comment by pwzgorilla** [comment]
这个跟raft没关系吗 raft不是已经不用了么
