### ISSUE TITLE
无法解析 http 服务

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#551]
time="2017-05-05 06:19:28" level=debug msg="resolve dns hostname 0.tt.admin.dataman.gateway.swan.com."
time="2017-05-05T06:19:28Z" level=debug msg="got request for hostname: 0.tt.admin.dataman.gateway.swan.com"
httputil: ReverseProxy read error during body copy: http: read on closed response body

**Comment by xiaods** [comment]
你没有配置dns服务器吧？

**Comment by xiaods** [comment]
@pangzheng 这个bug还在吗？

**Comment by pangzheng** [comment]
dns 是正常配置的

**Comment by pwzgorilla** [comment]
@pangzheng 老庞 这个bug是怎么出现的啊

**Comment by pangzheng** [comment]
使用swan 发一个服务，名字为 tt 。正常运行 proxy 节点，然后通过 dns 访问0.tt.admin.dataman.gateway.swan.com，proxy 返回日志。

**Comment by cmingxu** [comment]
已修复
