### ISSUE TITLE
swan master 节点健康检查异常

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#568]
新版本swan 健康检查只有一台leader 是正常的，其他非leader 节点健康检查是异常的。需要修改健康检查逻辑。

**Comment by pangzheng** [comment]
异常节点日志
Connected to 192.168.1.232:2181
Connected to 192.168.1.231:2181
Authenticated: id=169999577327796233, timeout=5000
Re-submitting `0` credentials after reconnect
Authenticated: id=97941983288623105, timeout=5000
Re-submitting `0` credentials after reconnect

**Comment by pangzheng** [comment]
确认是swan 新修改的高可用的非leader 节点健康检查逻辑需要修改。

**Comment by cmingxu** [comment]
@xiaods 原因是follower时候apiServer没开， 需要决定一下follower是否增加 /ping API

**Comment by xiaods** [comment]
@cmingxu 明白。开放API接口。从mesos/agent的例子，它是提供health 接口的。

**Comment by xiaods** [comment]
fixed by pwzgorilla.
