### ISSUE TITLE
the zk store is not production ready

### ISSUE THREAD

**Issue by bbklab** [Dataman-Cloud/swan#572]
- 内存map的global lock限制了并发数据请求。
  - 目前写操作先更新内存map，再更新zk，如果停止zk，但对外看起来数据读写依旧可以完成。
  - 只使用了zk的单个key存取所有数据，1限制并发 2 有可能超过zk单key的默认最大长度限制1M，测试部署30多个编排就会超过1M
  - zk 的数据目录增长太快，看zk日志和`atomic-store`的频繁更新删除有关

**Comment by xiaods** [comment]
yes, need PR

**Comment by xiaods** [comment]
@bbklab 遇到问题，就直接提交代码吧，不用等春明。
