### ISSUE TITLE
需要从swan manager的api中获得连接的agent的地址

### ISSUE THREAD

**Issue by xiaods** [Dataman-Cloud/swan#583]
每个swan agent连接当前都需要连接manager。但是swan manager命令没有提供查询manager API汇总地址。

**Comment by xiaods** [comment]
Current workflow, the agent start should be connect to manager directly, and the manager can't as a api server to list all agent list. we need talk about agent addr to platform, it is not elegant way.

**Comment by xiaods** [comment]
need zk feature to found the lead manager

**Comment by xiaods** [comment]
当前agent list 是暴露在agent的API接口上。

**Comment by pwzgorilla** [comment]
👍
