### ISSUE TITLE
任务分配主机不均匀

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#615]
3个slave节点，随机发布10个实例的应用，任务只分配到了2个节点上，1个节点上无任务。
其次被分配2个节点的实例数量也是非常不均匀，一个2个task,一个8个task

**Comment by xiaods** [comment]
调度策略优化

**Comment by xiaods** [comment]
适应bin-pack

**Comment by pwzgorilla** [comment]
已解决
