### ISSUE TITLE
swan proxy app 添加SRV 记录功能

### ISSUE THREAD

**Issue by ss75710541** [Dataman-Cloud/swan#624]
现在的proxy 是没有 app 的 SRV 记录的，需要增加

```
dig  @10.3.7.2 test.bridge.default.dataman.dataman.gateway.swan.com
```

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> @10.3.7.2 test.bridge.default.dataman.dataman.gateway.swan.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21408
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;test.bridge.default.dataman.dataman.gateway.swan.com. IN A

;; ANSWER SECTION:
test.bridge.default.dataman.dataman.gateway.swan.com. 3	IN A 10.3.7.2

;; Query time: 1 msec
;; SERVER: 10.3.7.2#53(10.3.7.2)
;; WHEN: Wed May 24 11:47:47 CST 2017
;; MSG SIZE  rcvd: 138

```
dig  @10.3.7.2 test.bridge.default.dataman.dataman.gateway.swan.com SRV
```

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> @10.3.7.2 test.bridge.default.dataman.dataman.gateway.swan.com SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49621
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;test.bridge.default.dataman.dataman.gateway.swan.com. IN SRV

;; Query time: 1 msec
;; SERVER: 10.3.7.2#53(10.3.7.2)
;; WHEN: Wed May 24 11:52:04 CST 2017
;; MSG SIZE  rcvd: 70

**Comment by xiaods** [comment]
有上下文吗？

**Comment by ss75710541** [comment]
新版swan 测试了，有SRV记录，可能是之前 的swan bug导致的没有SRV记录
