### ISSUE TITLE
swan proxy calico 网络同时解析到 宿主机 ip 和 calico ip

### ISSUE THREAD

**Issue by ss75710541** [Dataman-Cloud/swan#630]
dig appcalico.a.default.jyliu.dataman.swan.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> appcalico.a.default.jyliu.dataman.swan.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4467
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;appcalico.a.default.jyliu.dataman.swan.com. IN A

;; ANSWER SECTION:
appcalico.a.default.jyliu.dataman.swan.com. 3 IN A 10.3.7.6
appcalico.a.default.jyliu.dataman.swan.com. 3 IN A 10.0.0.1
appcalico.a.default.jyliu.dataman.swan.com. 3 IN A 10.3.7.7
appcalico.a.default.jyliu.dataman.swan.com. 3 IN A 10.3.7.6
appcalico.a.default.jyliu.dataman.swan.com. 3 IN A 10.0.0.2
appcalico.a.default.jyliu.dataman.swan.com. 3 IN A 10.0.0.3

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu May 25 14:52:15 CST 2017
;; MSG SIZE  rcvd: 408

**Comment by ss75710541** [comment]
最初时 解析是正常的，不知道是不是我重启过swan 后就异常了

**Comment by pwzgorilla** [comment]
@ss75710541  重启swan manager还是agent
