### ISSUE TITLE
关于跨防火墙网络(南北向)需求

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#650]
因为设计到灰度发布所以直接跨过proxy 使用srv来进行服务发现和路由的方式不能支持，故此有两种方法来实现跨防火墙服务转发。
1、增加 proxy 能力，对于服务映射对外访问端口，外部服务对接这个端口进行发现，参考ha/nginx
2、通过 swan json或者srv 提供标准接口数据(ip/port/权重等)，由bamboo或者 lua 刷新到 nginx或者ha

**Comment by xiaods** [comment]
支持L4/L7, http://confluence.dataman-inc.com/pages/viewpage.action?pageId=7700744

**Comment by bbklab** [comment]
related to #662, resolved by #661
