### ISSUE TITLE
swan srv 解析缺少 ADDITIONAL SECTION

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#653]
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> @192.168.1.216 dev2app.default.root.dataman.dataman.com srv
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34492
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dev2app.default.root.dataman.dataman.com. IN SRV

;; ANSWER SECTION:
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31005 6.dev2app.default.root.dataman.dataman.com.
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31006 0.dev2app.default.root.dataman.dataman.com.
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31007 1.dev2app.default.root.dataman.dataman.com.
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31008 2.dev2app.default.root.dataman.dataman.com.
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31009 3.dev2app.default.root.dataman.dataman.com.
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31003 4.dev2app.default.root.dataman.dataman.com.
dev2app.default.root.dataman.dataman.com. 3 IN SRV 0 0 31004 5.dev2app.default.root.dataman.dataman.com.

;; Query time: 1 msec
;; SERVER: 192.168.1.216#53(192.168.1.216)
;; WHEN: 四 6月 01 14:15:24 CST 2017
;; MSG SIZE  rcvd: 772

正常 srv 解析
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> calico.service.consul srv
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14463
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2

;; QUESTION SECTION:
;calico.service.consul.		IN	SRV

;; ANSWER SECTION:
calico.service.consul.	0	IN	SRV	1 1 2379 srymaster1.node.dataman.consul.
calico.service.consul.	0	IN	SRV	1 1 2379 sryslave1.node.dataman.consul.

;; ADDITIONAL SECTION:
srymaster1.node.dataman.consul.	0 IN	A	192.168.1.213
sryslave1.node.dataman.consul. 0 IN	A	192.168.1.216

;; Query time: 1 msec
;; SERVER: 192.168.1.213#53(192.168.1.213)
;; WHEN: 四 6月 01 14:15:47 CST 2017
;; MSG SIZE  rcvd: 145

**Comment by xiaods** [comment]
OK
