### ISSUE TITLE
constraint proposal

### ISSUE THREAD

**Issue by pwzgorilla** [Dataman-Cloud/swan#667]
```
constraint {
        attribute : "vcluster"
        operator  : "="
        value     : "dataman"
}
```
+ *attribute*(string) - Specifies the name  of attribute setting on mesos agent.

+ *operator*(string) - Specifies the comparison operator. Possible values include:
```
=
!=
>
>=
<
<=
~=
 contains
```
+ *value*(string) - Specifies the value to compare the attribute against using the specified operation.

constraint examples:
+ schedule all tasks on agent with attribute "vcluster:dataman".
```
constraint: [
{
  attribute : "vcluster"
   operator: "="
  value       : "dataman"
}
]
```
+ schedule all tasks on agent with attribute "disk_type:ssd".
```
constraint: [
{
  attribute : "disk_type"
   operator: "="
  value       : "ssd"
}
]
```
+ schedule all tasks on agent with "disk > 100G"
```
constraint: [
{
  attribute : "disk"
   operator: ">"
  value       : "100G"
}
]
```
+ scheduler all tasks on agent with attribute "vcluster:dataman" and with attribute "kernel.os: centos".
```
constraint: [
{
  attribute : "vcluster"
   operator: "="
  value       : "dataman"
},
{
  attribute : "kernel.os"
   operator: "="
  value       : "centos"
},
]
```
+ scheduler all tasks on linux box.
```
constraint: [
{
  attribute : "kernel.name"
   operator: "="
  value       : "linux"
}
]
```
In some cases, `operator` is optional. eg.:
```
constraint: [
{
  attribute : "vcluster"
  value       : "dev"
}
]
```
```
constraint: [
{
  attribute : "kernel.name"
  value       : "linux"
}
]
```

**Comment by xiaods** [comment]
我建议不要这样过度设计。
constraint filter就是一个过滤，有这么多需求吗？
从docker swarm的设计来看，它就支持一种：
-e constraint:storage==ssd

仅支持一个，==

**Comment by pwzgorilla** [comment]
swarm 好像俩 "==" "!="

**Comment by pwzgorilla** [comment]
那咱们支持三种可以不： 等于，不等于，约等于（相当于like）

**Comment by xiaods** [comment]
我觉得可以。支持的越少越好。

**Comment by pwzgorilla** [comment]
行那就先支持这三种

**Comment by pwzgorilla** [comment]
operator support: "==", "!=", "~=".

**Comment by pwzgorilla** [comment]
已支持
