### ISSUE TITLE
swan proxy 功能出现单点问题

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#682]
因为 swan proxy 在提供给 nat 服务时，需要需要解析到网关服务后再由网关进行转发。现有逻辑解析网关域名时 ，swan proxy 提供的地址是提供 dns 服务的swan proxy 地址，这样就变成了单点，无法扩展。这里需要提供的是所有正常的 swan proxy 地址。

当然这里如果按照流量区分，应该是东西或者南北向流量的 proxy 地址解析不同。

**Comment by xiaods** [comment]
2017-06-005	服务发现(DNS)	支持DNS模型的内部名字发现，提供swan dns空间	M	需要	需要	v0.1	 

在backlog中，我们确实规划了这块，差一个架构规划。
