### ISSUE TITLE
swan dns 解析有ttl

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#685]
因为是服务发现和健康检查，所以需要取消 ttl，或者可以设置

dig @192.168.1.216 nathttp.default.dataman.dataman.swan.com

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.216 nathttp.default.dataman.dataman.swan.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9300
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nathttp.default.dataman.dataman.swan.com. IN A

;; ANSWER SECTION:
nathttp.default.dataman.dataman.swan.com. 3 IN A 192.168.1.217

;; Query time: 26 msec
;; SERVER: 192.168.1.216#53(192.168.1.216)
;; WHEN: Thu Jun 22 15:27:47 2017
;; MSG SIZE  rcvd: 114

dig @192.168.1.216 nathttp.default.dataman.dataman.gateway.swan.com

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.216 nathttp.default.dataman.dataman.gateway.swan.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59616
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nathttp.default.dataman.dataman.gateway.swan.com. IN A

;; ANSWER SECTION:
nathttp.default.dataman.dataman.gateway.swan.com. 3 IN A 192.168.1.216

;; Query time: 32 msec
;; SERVER: 192.168.1.216#53(192.168.1.216)
;; WHEN: Thu Jun 22 15:28:07 2017
;; MSG SIZE  rcvd: 130

**Comment by bbklab** [comment]
fixed by  #686
