### ISSUE TITLE
调用/v1/pruge接口 清理应用，卡住

### ISSUE THREAD

**Issue by ss75710541** [Dataman-Cloud/swan#696]
![image](https://user-images.githubusercontent.com/5858487/27619762-657a0a8e-5bf7-11e7-8eac-6466eae65608.png)

**Comment by ss75710541** [comment]
卡了半小时以上了

**Comment by xiaods** [comment]
this api endpoint is outdate, please re-check the api's usage. if need this feature, please let me know.
