### ISSUE TITLE
cpu 占用100%

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#698]
swan 版本centos7-swan:v0.1.11-208-g1123491
cpu 异常占用 100%，下面是cpu占用、日志

![4162f7b1-215e-4ec8-b188-fe04c4d6c187](https://user-images.githubusercontent.com/7556687/27627775-977ddee8-5c1f-11e7-99df-d4d8dd344c6a.png)
![dc833d34-2a62-41ee-a1a3-ac1fc7a6130d](https://user-images.githubusercontent.com/7556687/27627778-98eb045e-5c1f-11e7-8c39-e6211b19be60.png)
![777a76ac-12c4-4e26-a036-9bf0da352584](https://user-images.githubusercontent.com/7556687/27627782-9a2a4a5a-5c1f-11e7-939b-1149db0b4ac0.png)

**Comment by xiaods** [comment]
这种测试需要一个压力平台不断的测试。

**Comment by pwang7** [comment]
搞个持续的测试环境吧。

-王璞

**Comment by pwzgorilla** [comment]
这个是旧版的swan

**Comment by pwzgorilla** [comment]
吧

**Comment by xiaods** [comment]
fixed
