### ISSUE TITLE
API upgrade interface refactor proposal

### ISSUE THREAD

**Issue by xiaods** [Dataman-Cloud/swan#716]
1、POST	/v1/apps/{app_id}/versions	Create a version for a app
remove this endpoint, don't need it any more
2、PUT	/v1/apps/{app_id}	Rolling update a app
**knowledge**: PUT should only be used if you're replacing a resource in it's entirety.
``` 
 HTTP/1.1 201 Created
  Content-Type: application/json

  {
      "id": "1498791358276219466"
      "versionId":"1498791358276219465"
  }
```

the upgrade strategy is can set manully or automate 

3. if you want to canary, you can set a flag to open the feature. please extend this api:
POST /v1/apps/{app_id}/update

key : canary is optional
```
POST /v1/apps/nginx0r2.default.xcm.dataman/update HTTP/1.1
Content-Type: application/json
{
    "instances": 5, 
    "canary": {
        "value": 0.1,
    }
}
```

**Comment by xiaods** [comment]
any update

**Comment by pwzgorilla** [comment]
现在提供两个更新的api，一个是通用型的update api， 一个是用于灰度的update api。

+ 通用型的update: PUT /v1/update 
```
 通用型的update不关心灰度，只提供一个新的version和一个update策略，然后根据策略一次性完成全部实例的滚动更新。
```
+ 灰度update: PUT /v1/canary 
```
灰度更新需要提供更新的版本和要更新的实例数，还要提供一个灰度值。用于做灰度发布用。
```
