### ISSUE TITLE
swan 删除接口无法保证 mesos 上被删除的任务被回收

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#784]
现在 swan 删除任务执行后，会向 mesos 发送删除后，swan 就删除了自己的任务，而因 mesos 异常导致任务没回收的 swan 任务， swan 就没有能力管理了(因为对于swan来说，这些任务已经 不存在了)

**Comment by xiaods** [comment]
这是一个设计问题，而不是一个bug。
