### ISSUE TITLE
通过扩展docker compose v3 YAML语法来扩展编排

### ISSUE THREAD

**Issue by bbklab** [Dataman-Cloud/swan#887]
目前通过一个json字段  `yaml_extra` 来扩展，使用不方便，需要将现有扩展通过 YAML 语法实现。

 - [x] 编排API使用纯YAML格式重构
 - [x] 编排中的变量替换
 - [x] 新的编排API文档
 - [x] 测试和确认ComposeV3  YAML参数
   - [x] 支持的参数
   - [x] 不支持的参数
   - [x] 扩展的参数

**Comment by xiaods** [comment]
docker cloud在扩展compose的时候，也遇到同样的问题。有一些参数是不支持的。

https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/

`build
external_links
env_file
 `
