### ISSUE TITLE
API: 创建应用时url后多了/ 请求返回app列表

### ISSUE THREAD

**Issue by addozhang** [Dataman-Cloud/swan#913]
请求

curl -X POST \
  http://localhost:15016/v1/apps/ \
  -H 'accept-encoding: gzip,deflate' \
  -H 'authorization: Basic ZGV2OkFkbWluMTIz' \
  -H 'cache-control: no-cache' \
  -H 'connection: Keep-Alive' \
  -H 'content-length: 912' \
  -H 'content-type: application/json' \
  -H 'host: 127.0.0.1:15016' \
  -H 'postman-token: a6e9156b-346d-60ab-20b5-e4d5beb453e8' \
  -H 'user-agent: Apache-HttpClient/4.5.2 (Java/1.8.0_141)' \
  -d '{"name":"nginxtest","cpus":1.0,"mem":512.0,"disk":0,"runAs":"dev","cluster":"dev","instances":1,"constraints":[{"attribute":"vcluster","operator":"\u003d\u003d","value":"dev"}],"container":{"docker":{"image":"nginx","network":"bridge","forcePullImage":false,"privileged":false,"parameters":[{"key":"key","value":"label"},{"key":"value","value":"DM_USER_NAME\u003ddev"},{"key":"key","value":"label"},{"key":"value","value":"DM_GROUP_NAME\u003ddev"},{"key":"key","value":"label"},{"key":"value","value":"DM_VCLUSTER\u003ddev"},{"key":"key","value":"label"},{"key":"value","value":"DM_TENANT_ID\u003d1"}],"portMappings":[{"name":"port0","protocol":"tcp","containerPort":24500,"hostPort":0}]},"type":"DOCKER","volumes":[{"hostPath":"/apps/logs","containerPath":"/apps/logs","mode":"RW"}]},"labels":{"DM_GROUP_ID":"2","DM_USER_NAME":"dev","DM_USER_ID":"2","DM_VCLUSTER":"dev","DM_TENANT_ID":"1","DM_VCLUSTER_ID":"1"}}'

**Comment by bbklab** [comment]
没有这样的问题 😞
