### ISSUE TITLE
task_status的返回值问题

### ISSUE THREAD

**Issue by addozhang** [Dataman-Cloud/swan#923]
有大写 有小 能否统一? 
task_status与status的字段有何关联?
task_status都有哪些值?
status都有哪些值

"tasks_status": {
      "TASK_UNKNOWN": 1
    },

  "tasks_status": {
    "pending": 2
  },

 "tasks_status": {
    "TASK_RUNNING": 5
  },

**Comment by bbklab** [comment]
这里直接使用了mesos 的task status 状态定义，共14种，见：
https://github.com/Dataman-Cloud/swan/blob/master/mesosproto/mesos.pb.go#L201
和
https://github.com/Dataman-Cloud/swan/blob/master/mesosproto/mesos.proto#L1506

另加一个状态 `pending` 表示TASK在swan上创建，但尚未在mesos上创建

**Comment by bbklab** [comment]
`status`  只有两个状态：
  - available :  至少一个task是  `TASK_RUNNING` 
  - unavailable : 所有task都不是 `TASK_RUNNING`
